version: "3.8"

services:
  postgres:
    image: postgres:14.4
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - modules/testing/testing-domain-base/src/main/resources/postgres.env

  elasticsearch:
    image: elasticsearch:7.17.5
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    env_file:
      - modules/testing/testing-domain-base/src/main/resources/elasticsearch.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
