@startuml

skinparam shadowing false

actor "User" as user
participant "Employees Module" as module
database "Database" as db
queue "Message Broker" as broker
database "Search Index" as si

== Creation ==

user -> module: add new employee
activate module
module -> db: insert
module -> broker: publish event
activate broker
user <- module
deactivate module
module <- broker: notify listener
deactivate broker
activate module
module -> si: insert
deactivate module

== Update ==

user -> module: update existing employee
activate module
module -> db: update
module -> broker: publish event
activate broker
user <- module
deactivate module
module <- broker: notify listener
deactivate broker
activate module
module -> si: update
deactivate module

== Deletion ==

user -> module: delete existing employee
activate module
module -> db: delete
module -> broker: publish event
activate broker
user <- module
deactivate module
module <- broker: notify listener
deactivate broker
activate module
module -> si: delete
deactivate module

@enduml
