@startuml

skinparam shadowing false

actor "Admin" as admin
participant "Employees Module" as module
database "Search Index" as si
database "Database" as db

admin -> module: trigger task
activate module
module -> si: reset index (delete + create)
activate si
module <-- si
deactivate si
module -> db: stream all employees
activate db
loop
module -> si: index employee
activate si
deactivate si
end
module <-- db
deactivate db
admin <-- module
deactivate module
@enduml
