spring.config.import:
  - classpath:domain-employees-config.yml
  - classpath:domain-projects-config.yml
  - classpath:domain-skills-config.yml

---

security:
  users:
    basic-auth:
      - username: "user"
        password: "resu"
        authorities:
          - "SCOPE_API"
          - "ROLE_USER"
      - username: "admin"
        password: "nimda"
        authorities:
          - "SCOPE_API"
          - "SCOPE_GRAPHIQL"
          - "ROLE_USER"
          - "ROLE_ADMIN"
      - username: "actuator"
        password: "rotautca"
        authorities:
          - "SCOPE_ACTUATOR"

server:
  shutdown: graceful

spring:
  graphql:
    schema:
      locations:
        - classpath:/graphql/base/**
        - classpath:/graphql/employees/**
        - classpath:/graphql/projects/**
        - classpath:/graphql/skills/**
