logging:
  level:
    root: INFO
    skillmanagement: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/database"
    username: user
    password: password
  elasticsearch:
    rest:
      uris: "http://localhost:9200"
  graphql:
    graphiql:
      enabled: true
    path: /api/graphql
    schema:
      printer:
        enabled: true
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: false
  rabbitmq:
    host: localhost
    port: 5672
